# -*- coding: utf-8 -*-
"""AluraStoreLatam challenge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Q68R1t1t8-fgwUdbQ1BHOrRUN50vawq

### Importación de datos
"""

import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

"""#1. Análisis de facturación


"""

tienda["Tienda"] = "Tienda 1"
tienda2["Tienda"] = "Tienda 2"
tienda3["Tienda"] = "Tienda 3"
tienda4["Tienda"] = "Tienda 4"

todas = pd.concat([tienda, tienda2, tienda3, tienda4])

ingresos = todas.groupby("Tienda")["Precio"].sum().astype(int)
ingresos

"""# 2. Ventas por categoría"""

categoria_ventas = todas.groupby(["Tienda", "Categoría del Producto"])["Producto"].count()
categoria_ventas

categoria_ventas.sort_values(ascending=False)

"""# 3. Calificación promedio de la tienda

"""

calificaciones = todas.groupby("Tienda")["Calificación"].mean()
calificaciones

calificaciones.round(2)

"""# 4. Productos más y menos vendidos"""

productos = todas.groupby(["Tienda", "Producto"])["Producto"].count()
productos

#mas vendido
productos.sort_values(ascending=False)

#menos vendido
productos.sort_values()

productos.sort_values(ascending=False).head(10).plot(kind="bar")

"""# 5. Envío promedio por tienda"""

envio_promedio = todas.groupby("Tienda")["Costo de envío"].mean()
envio_promedio

envio_promedio.round(2)

"""## **Graficos**"""

ingresos = todas.groupby("Tienda")["Precio"].sum()

ingresos.plot(kind="bar", title="Ingresos por tienda")

categorias = todas.groupby("Categoría del Producto")["Producto"].count()

categorias.sort_values(ascending=False).head(10).plot(kind="bar", title="Categorías más vendidas")

calificaciones = todas.groupby("Tienda")["Calificación"].mean()

calificaciones.plot(kind="bar", title="Calificación promedio por tienda")

"""**De acuerdo al analisis, el sr. Juan debería quedarse  con la tienda 2, debido a que es la segunda que presenta más ingresos, donde hay productos más vendidos y su calificación es la 2da mejor.**"""